file=open(r"C:\Users\lab\File1.txt", "w")
file.write("This is a python program")
file.close()

file=open(r"C:\Users\lab\File1.txt", "r")
content=file.read(24)
print(content)
file.close()
file=open(r"C:\Users\lab\File1.txt", "r")
content1=file.readline()
print(content1)
file.close()
file=open(r"C:\Users\lab\File1.txt", "r")
content2=file.readlines()
print(content2)
file.close()
